version: '3'
services:
  myapp:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=/tmp
      - XDG_SESSION_TYPE=x11
    ports:
      - "8080:8080"  # Puerto para la aplicación si es necesario
